import type { ContentItem } from './types';

const img = {
  dj1: 'https://images.pexels.com/photos/26978133/pexels-photo-26978133.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj2: 'https://images.pexels.com/photos/14483028/pexels-photo-14483028.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj3: 'https://images.pexels.com/photos/7258865/pexels-photo-7258865.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj4: 'https://images.pexels.com/photos/20612481/pexels-photo-20612481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj5: 'https://images.pexels.com/photos/6782327/pexels-photo-6782327.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj6: 'https://images.pexels.com/photos/7715519/pexels-photo-7715519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj7: 'https://images.pexels.com/photos/5268174/pexels-photo-5268174.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj8: 'https://images.pexels.com/photos/18527859/pexels-photo-18527859.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj9: 'https://images.pexels.com/photos/7715459/pexels-photo-7715459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  dj10: 'https://images.pexels.com/photos/5949085/pexels-photo-5949085.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio1: 'https://images.pexels.com/photos/7243780/pexels-photo-7243780.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio2: 'https://images.pexels.com/photos/7450059/pexels-photo-7450059.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio3: 'https://images.pexels.com/photos/28003176/pexels-photo-28003176.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio4: 'https://images.pexels.com/photos/8132717/pexels-photo-8132717.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio5: 'https://images.pexels.com/photos/35307143/pexels-photo-35307143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio6: 'https://images.pexels.com/photos/5657668/pexels-photo-5657668.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio7: 'https://images.pexels.com/photos/5749192/pexels-photo-5749192.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  studio8: 'https://images.pexels.com/photos/7173393/pexels-photo-7173393.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert1: 'https://images.pexels.com/photos/12787862/pexels-photo-12787862.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert2: 'https://images.pexels.com/photos/13230484/pexels-photo-13230484.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert3: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert4: 'https://images.pexels.com/photos/8186275/pexels-photo-8186275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert5: 'https://images.pexels.com/photos/1613240/pexels-photo-1613240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert6: 'https://images.pexels.com/photos/1179581/pexels-photo-1179581.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  concert7: 'https://images.pexels.com/photos/167605/pexels-photo-167605.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};

const standardQualities = [
  { label: '144p', resolution: '256x144', available: true },
  { label: '240p', resolution: '426x240', available: true },
  { label: '360p', resolution: '640x360', available: true },
  { label: '480p', resolution: '854x480', available: true },
  { label: '720p', resolution: '1280x720', available: true },
  { label: '1080p', resolution: '1920x1080', available: true },
  { label: '1440p', resolution: '2560x1440', available: false },
  { label: '2160p', resolution: '3840x2160', available: false },
];

const hdQualities = [
  { label: '144p', resolution: '256x144', available: true },
  { label: '240p', resolution: '426x240', available: true },
  { label: '360p', resolution: '640x360', available: true },
  { label: '480p', resolution: '854x480', available: true },
  { label: '720p', resolution: '1280x720', available: true },
  { label: '1080p', resolution: '1920x1080', available: true },
  { label: '1440p', resolution: '2560x1440', available: true },
  { label: '2160p', resolution: '3840x2160', available: true },
];

const audioFormats = [
  { format: 'mp3' as const, bitrate: '128 kbps', available: true },
  { format: 'mp3' as const, bitrate: '192 kbps', available: true },
  { format: 'mp3' as const, bitrate: '256 kbps', available: true },
  { format: 'mp3' as const, bitrate: '320 kbps', available: true },
  { format: 'aac' as const, bitrate: '256 kbps', available: true },
  { format: 'wav' as const, bitrate: '1411 kbps', available: true },
  { format: 'flac' as const, bitrate: 'lossless', available: false },
];

const limitedAudioFormats = [
  { format: 'mp3' as const, bitrate: '128 kbps', available: true },
  { format: 'mp3' as const, bitrate: '192 kbps', available: true },
  { format: 'aac' as const, bitrate: '256 kbps', available: true },
];

export const defaultContent: ContentItem[] = [
  {
    id: 'c1',
    title: 'Neon Nights Live Set - Electronic Festival 2025',
    channel: 'DJ Pulse',
    thumbnail: img.dj1,
    duration: '1:24:30',
    durationSeconds: 5070,
    type: 'video',
    views: '2.4M',
    publishedAt: '2025-07-15',
    description: 'Experience the full live set from DJ Pulse at the Neon Nights Electronic Festival. Over an hour of pure energy with exclusive tracks and remixes.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c2',
    title: 'Midnight Mix Session Vol. 3 - Deep House',
    channel: 'Luna Beats',
    thumbnail: img.dj2,
    duration: '58:12',
    durationSeconds: 3492,
    type: 'music',
    views: '890K',
    publishedAt: '2025-06-20',
    description: 'A deep house journey through the midnight hours. Perfect for late sessions and focused work.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c3',
    title: 'Studio Session: Making a Track from Scratch',
    channel: 'Producer Hub',
    thumbnail: img.studio1,
    duration: '32:45',
    durationSeconds: 1965,
    type: 'video',
    views: '456K',
    publishedAt: '2025-08-01',
    description: 'Watch a complete studio session as we build an electronic track from scratch using synths, drum machines, and effects.',
    qualities: hdQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c4',
    title: 'Techno Festival Highlights - Summer Tour',
    channel: 'Beat Factory',
    thumbnail: img.concert2,
    duration: '15:30',
    durationSeconds: 930,
    type: 'video',
    views: '1.2M',
    publishedAt: '2025-07-28',
    description: 'The best moments from the Summer Techno Tour across Europe. Featuring top DJs and incredible crowds.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c5',
    title: 'Lo-Fi Beats to Relax/Study to',
    channel: 'Chill Vibes',
    thumbnail: img.studio7,
    duration: '2:00:00',
    durationSeconds: 7200,
    type: 'music',
    views: '5.6M',
    publishedAt: '2025-05-10',
    description: 'Two hours of relaxing lo-fi beats perfect for studying, reading, or unwinding after a long day.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c6',
    title: 'How to DJ: Beginner to Pro Course',
    channel: 'MixMaster Academy',
    thumbnail: img.dj7,
    duration: '45:20',
    durationSeconds: 2720,
    type: 'video',
    views: '678K',
    publishedAt: '2025-06-05',
    description: 'Learn everything you need to start DJing. From basic beat matching to advanced transitions and effects.',
    qualities: hdQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c7',
    title: 'Synthwave Collection - Retro 80s Vibes',
    channel: 'RetroWave',
    thumbnail: img.concert5,
    duration: '1:15:00',
    durationSeconds: 4500,
    type: 'playlist',
    views: '3.1M',
    publishedAt: '2025-04-22',
    description: 'A curated playlist of the best synthwave tracks. Nostalgic 80s sounds with modern production.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c8',
    title: 'Underground Club Set - Bass Drop Special',
    channel: 'Bass Nation',
    thumbnail: img.dj3,
    duration: '1:02:15',
    durationSeconds: 3735,
    type: 'music',
    views: '920K',
    publishedAt: '2025-08-05',
    description: 'Heavy bass, underground vibes, and exclusive drops. Recorded live at an intimate club venue.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c9',
    title: 'Music Production Tips - Mixing Bass',
    channel: 'Studio Wizard',
    thumbnail: img.studio2,
    duration: '18:42',
    durationSeconds: 1122,
    type: 'video',
    views: '234K',
    publishedAt: '2025-07-30',
    description: 'Professional tips for mixing bass in your tracks. Learn EQ techniques, compression, and layering.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c10',
    title: 'Live Concert: Electronic Symphony',
    channel: 'Orchestra Digital',
    thumbnail: img.concert3,
    duration: '1:45:00',
    durationSeconds: 6300,
    type: 'video',
    views: '1.8M',
    publishedAt: '2025-06-12',
    description: 'A unique fusion of classical orchestra and electronic music. Recorded live with full visual show.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c11',
    title: 'Quick Mix: 60 Second Transition',
    channel: 'DJ Spark',
    thumbnail: img.dj9,
    duration: '0:58',
    durationSeconds: 58,
    type: 'short',
    views: '4.2M',
    publishedAt: '2025-08-10',
    description: 'A lightning-fast mix transition in under 60 seconds. Watch the magic happen.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: false,
    source: 'youtube',
  },
  {
    id: 'c12',
    title: 'Vinyl Collection Tour - Rare Electronic Presses',
    channel: 'Wax Museum',
    thumbnail: img.studio3,
    duration: '28:15',
    durationSeconds: 1695,
    type: 'video',
    views: '345K',
    publishedAt: '2025-05-25',
    description: 'Take a tour through a rare vinyl collection featuring limited electronic music pressings from the 90s and 2000s.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c13',
    title: 'Ambient Soundscape - Forest Meditation',
    channel: 'Nature Waves',
    thumbnail: img.concert1,
    duration: '3:00:00',
    durationSeconds: 10800,
    type: 'music',
    views: '890K',
    publishedAt: '2025-03-15',
    description: 'Three hours of ambient soundscape blending forest sounds with gentle electronic textures for meditation.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c14',
    title: 'Drum & Bass Anthology - Full Mix',
    channel: 'Breakbeat Central',
    thumbnail: img.dj4,
    duration: '1:30:00',
    durationSeconds: 5400,
    type: 'music',
    views: '1.5M',
    publishedAt: '2025-07-01',
    description: 'The ultimate drum and bass anthology. High energy from start to finish with classic and modern tracks.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c15',
    title: 'Behind the Decks: DJ Interview Series',
    channel: 'Music Talk',
    thumbnail: img.dj6,
    duration: '22:10',
    durationSeconds: 1330,
    type: 'video',
    views: '156K',
    publishedAt: '2025-08-15',
    description: 'Exclusive interviews with top DJs about their creative process, gear, and the stories behind their biggest sets.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c16',
    title: 'Festival Main Stage - Closing Set',
    channel: 'Neon Wave',
    thumbnail: img.concert6,
    duration: '2:00:00',
    durationSeconds: 7200,
    type: 'video',
    views: '3.5M',
    publishedAt: '2025-08-12',
    description: 'The epic closing set from the main stage. Two hours of peak energy, pyrotechnics, and unforgettable moments.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c17',
    title: 'Modular Synth Jam - Ambient Patch',
    channel: 'Patch Work',
    thumbnail: img.studio4,
    duration: '12:30',
    durationSeconds: 750,
    type: 'video',
    views: '89K',
    publishedAt: '2025-08-08',
    description: 'A live modular synth jam exploring ambient textures and evolving soundscapes.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c18',
    title: 'Top 50 Electronic Tracks of 2025',
    channel: 'Chart Watch',
    thumbnail: img.dj5,
    duration: '2:45:00',
    durationSeconds: 9900,
    type: 'playlist',
    views: '6.7M',
    publishedAt: '2025-08-01',
    description: 'The definitive list of the top 50 electronic tracks of 2025. Curated by industry experts and listener votes.',
    qualities: hdQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c19',
    title: 'Quick Beat: Making a Trap Loop',
    channel: 'Beat Maker',
    thumbnail: img.dj10,
    duration: '0:45',
    durationSeconds: 45,
    type: 'short',
    views: '2.1M',
    publishedAt: '2025-08-14',
    description: 'Watch a trap beat loop come together in 45 seconds.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: false,
    source: 'youtube',
  },
  {
    id: 'c20',
    title: 'Analog Warmth: Recording with Tape',
    channel: 'Vintage Sound',
    thumbnail: img.studio5,
    duration: '35:20',
    durationSeconds: 2120,
    type: 'video',
    views: '267K',
    publishedAt: '2025-07-18',
    description: 'Exploring the warmth of analog tape recording. Comparing digital vs analog with side-by-side examples.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c21',
    title: 'Crowd Reaction: Best Drop Moments',
    channel: 'Festival Vibes',
    thumbnail: img.concert7,
    duration: '8:15',
    durationSeconds: 495,
    type: 'video',
    views: '5.3M',
    publishedAt: '2025-08-03',
    description: 'The most epic crowd reactions to bass drops at major electronic festivals around the world.',
    qualities: hdQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c22',
    title: 'Headphone Mix: ASMR DJ Session',
    channel: 'Quiet Storm',
    thumbnail: img.studio6,
    duration: '40:00',
    durationSeconds: 2400,
    type: 'music',
    views: '780K',
    publishedAt: '2025-06-28',
    description: 'An ASMR-style DJ session designed for headphone listening. Subtle textures and intimate mixing.',
    qualities: standardQualities,
    audioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c23',
    title: 'Sound Design: Creating Bass from Scratch',
    channel: 'Synth Lab',
    thumbnail: img.studio8,
    duration: '25:50',
    durationSeconds: 1550,
    type: 'video',
    views: '198K',
    publishedAt: '2025-08-06',
    description: 'Learn professional sound design techniques for creating powerful bass sounds from scratch.',
    qualities: standardQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
  {
    id: 'c24',
    title: 'Festival Aftermovie - Electric Nights 2025',
    channel: 'Electric Nights',
    thumbnail: img.concert4,
    duration: '10:00',
    durationSeconds: 600,
    type: 'video',
    views: '1.9M',
    publishedAt: '2025-08-16',
    description: 'The official aftermovie capturing the best moments of Electric Nights Festival 2025.',
    qualities: hdQualities,
    audioFormats: limitedAudioFormats,
    downloadable: true,
    source: 'youtube',
  },
];
